import { $, icon, esc, mount, heading, field, busy, toast, errorMessage } from '../ui.js';
import { getUser, profileData, updateProfile, api, unwrap } from '../data.js';
const brand=`<a class="wordmark" href="signin.html"><span class="mark">${icon('spark')}</span>PRELUDE</a>`;
export async function renderAuth(page,root){
 if(page==='intro'){intro(root);return}
 if(page==='reset'){reset(root);return}
 let user=await getUser();
 if(user&&page==='signin'){location.replace('index.html');return}
 let credentials=null,proof=null,cooldown=0;
 const frame=html=>mount(root,brand+html);
 const feedback=(id,error)=>{$(id).textContent=error?.friendly||'We couldn’t continue. Please check your details and try again.'};
 const google=async()=>{const {error}=await supabaseClient.auth.signInWithOAuth({provider:'google',options:{redirectTo:new URL('signup.html',location.href).href}});if(error)throw error};
 function login(){frame(heading('WELCOME BACK','Your next moment awaits.','Sign in and pick up where you left off.')+`<div class="glass"><form class="stack" id="loginForm">${field('Email','email','email','','autocomplete="email" required')}${field('Password','password','password','','autocomplete="current-password" required')}<p class="form-error" id="authError" role="alert"></p><a href="reset.html" class="muted auth-recovery">Forgot password?</a><button class="btn primary full" type="submit">Sign in${icon('arrow')}</button></form><div class="divider">OR</div><button id="google" class="btn full">Continue with Google</button></div><p class="auth-foot">New to Prelude? <a href="signup.html">Create an account</a></p>`);
 $('#loginForm').onsubmit=busy($('#loginForm button'),async e=>{const fd=new FormData(e.target);const result=await supabaseClient.auth.signInWithPassword({email:fd.get('email').trim(),password:fd.get('password')});if(result.error){$('#authError').textContent='Unable to sign in. Check your email and password, or verify your email first.';return}location.replace('index.html')});$('#google').onclick=busy($('#google'),google)}
 function account(){frame(heading('PLAN IT. LIVE IT. REMEMBER IT.','Something worth preparing for.','Start with an email and a password. No phone number needed.')+`<div class="glass"><div class="stepper"><span class="done"></span><span></span><span></span></div><form id="accountForm" class="stack">${field('Email','email','email','','autocomplete="email" required maxlength="254"')}${field('Password','password','password','','autocomplete="new-password" minlength="8" maxlength="128" required')}${field('Confirm password','confirm','password','','autocomplete="new-password" required')}<p class="form-error" id="authError" role="alert"></p><button class="btn primary full">Continue${icon('arrow')}</button></form><div class="divider">OR</div><button id="google" class="btn full">Continue with Google</button></div><p class="auth-foot">Already have an account? <a href="signin.html">Sign in</a></p>`);
 $('#accountForm').onsubmit=busy($('#accountForm button'),async e=>{const fd=new FormData(e.target);if(fd.get('password')!==fd.get('confirm')){$('#authError').textContent='Your passwords don’t match.';return}credentials={email:fd.get('email').trim(),password:fd.get('password')};try{const sent=await api('/api/email/send',{method:'POST',body:{email:credentials.email}});cooldown=Date.now()+(sent.cooldown||0)*1000;verify()}catch(e){feedback('#authError',e)}});$('#google').onclick=busy($('#google'),google)}
 function verify(){frame(heading('STEP 2 OF 3','Check your inbox.',`Enter the six-digit code sent to ${credentials.email}.`)+`<div class="glass"><div class="stepper"><span class="done"></span><span class="done"></span><span></span></div><form id="verifyForm" class="stack">${field('Verification code','code','text','','inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" minlength="6" maxlength="6" required')}<p id="authError" class="form-error" role="alert"></p><button class="btn primary full">Verify email${icon('check')}</button></form><button class="btn full section" id="resend">Resend code</button><button class="text-btn full" id="changeEmail">Use a different email</button></div>`);$('#verifyForm input').focus();
 $('#verifyForm').onsubmit=busy($('#verifyForm button'),async e=>{try{const result=await api('/api/email/verify',{method:'POST',body:{email:credentials.email,code:new FormData(e.target).get('code')}});proof=result.verificationToken;profile()}catch(e){feedback('#authError',e)}});
 $('#resend').onclick=busy($('#resend'),async()=>{if(Date.now()<cooldown){toast(`Please wait ${Math.ceil((cooldown-Date.now())/1000)} seconds.`);return}const sent=await api('/api/email/send',{method:'POST',body:{email:credentials.email}});cooldown=Date.now()+(sent.cooldown||0)*1000;toast('A new code is on its way.');$('#verifyForm input').value=''});$('#changeEmail').onclick=()=>{credentials=null;proof=null;account()}}
 function profile(){const current=user?profileData(user):{};frame(heading('ONE LAST THING','Make yourself at home.','Tell us your name and what you’d like to be called.')+`<div class="glass"><div class="stepper"><span class="done"></span><span class="done"></span><span class="done"></span></div><form id="profileForm" class="stack">${field('Your name','name','text',current.name||user?.user_metadata?.full_name||'','autocomplete="name" maxlength="80" required')}${field('Preferred name','nickname','text',current.nickname||'','autocomplete="nickname" maxlength="40" required')}<p class="form-error" id="authError" role="alert"></p><button class="btn primary full">Enter Prelude${icon('arrow')}</button></form></div>`);
 $('#profileForm').onsubmit=busy($('#profileForm button'),async e=>{const fd=new FormData(e.target);const values={name:fd.get('name').trim(),nickname:fd.get('nickname').trim(),profileComplete:true};if(!values.name||!values.nickname){$('#authError').textContent='Please complete both names.';return}try{if(user){user=await updateProfile(user,values)}else{await api('/api/auth/signup',{method:'POST',body:{...credentials,...values,verificationToken:proof}});const login=await supabaseClient.auth.signInWithPassword(credentials);unwrap(login);user=login.data.user;credentials=null;proof=null}location.replace('index.html')}catch(e){feedback('#authError',e)}})}
 if(page==='signin')login();else if(user){if(profileData(user).profileComplete)location.replace('index.html');else profile()}else account();
}
function intro(root){let step=0;const steps=[['Plan it.','A little preparation makes a meaningful difference. Give your next event a name, a date, and a place to grow.','goal'],['Live it.','Arrive ready. Keep the details, directions and moments of your day together, so you can be there for it.','spark'],['Remember it.','Some moments deserve more than a date on a calendar. Keep the photos, reflections and story of yours.','photo']];function render(){const [title,text,symbol]=steps[step];mount(root,brand+`<div class="intro-visual"><div class="orbit"></div><div class="orb"></div><div class="intro-symbol">${icon(symbol)}</div></div><div class="intro-text">${heading('YOUR MOMENTS, WITH INTENTION',title,text)}<div class="intro-dots">${steps.map((_,i)=>`<span class="${i===step?'active':''}"></span>`).join('')}</div><button class="btn primary full" id="nextIntro">${step===2?'Let’s begin':'Continue'}${icon('arrow')}</button>${step?'<button class="text-btn" id="backIntro">Back</button>':''}</div><p class="footer-note">Plan it. Live it. Remember it.</p>`);$('#nextIntro').onclick=()=>{if(step===2){try{localStorage.setItem('prelude-intro-v1','done')}catch{}location.replace('signin.html')}else{step++;render()}};if(step)$('#backIntro').onclick=()=>{step--;render()}}render()}
function reset(root){const recovery=new URLSearchParams(location.search).get('mode')==='set'||location.hash.includes('type=recovery');mount(root,brand+heading('ACCOUNT ACCESS',recovery?'A fresh start.':'Let’s get you back in.',recovery?'Choose a new password.':'We’ll email a secure link to reset your password.')+`<div class="glass"><form class="stack" id="resetForm">${recovery?field('New password','password','password','','autocomplete="new-password" minlength="8" required'):field('Email','email','email','','autocomplete="email" required')}<button class="btn primary full">${recovery?'Save password':'Send reset link'}</button><p class="form-error" role="status" id="resetMessage"></p></form></div><p class="auth-foot"><a href="signin.html">Back to sign in</a></p>`);$('#resetForm').onsubmit=busy($('#resetForm button'),async e=>{const fd=new FormData(e.target);if(recovery){unwrap(await supabaseClient.auth.updateUser({password:fd.get('password')}));location.replace('signin.html')}else{unwrap(await supabaseClient.auth.resetPasswordForEmail(fd.get('email').trim(),{redirectTo:new URL('reset.html?mode=set',location.href).href}));$('#resetMessage').textContent='If an account exists for that email, a reset link is on its way.'}})}
